### ISSUE TITLE
RECOMMEND/VOTE Papers for the 1st session

### ISSUE THREAD

**Issue by sxjscience** [ML-HK/paper-discussion-group#1]
We can recommend some papers for further discussion under this issue. Include a link to the paper + the conference name and other related information (like the abstract, some basic descriptions, links to samples code or online demonstrations).

Please only include one topic per comment. For example, if you propose to discuss "paper X" which is heavily based on "paper Y" and you believe both have to be read together (possibly over multiple weeks) just create one comment for that. If you propose two unrelated papers please create two comments.

The paper recommendation period ends up on **2016/09/18** and the voting period ends up on **2016/09/20**.

Please vote using the "Thumbs up" emoji.

**Comment by leezu** [comment]
[**WaveNet: A Generative Model for Raw Audio**](http://arxiv.org/abs/1609.03499)
(arXiv - submitted on 12 Sep 2016)
 _This paper introduces WaveNet, a deep neural network for generating raw audio waveforms. The model is fully probabilistic and autoregressive, with the predictive distribution for each audio sample conditioned on all previous ones; nonetheless we show that it can be efficiently trained on data with tens of thousands of samples per second of audio. When applied to text-to-speech, it yields state-of-the-art performance, with human listeners rating it as significantly more natural sounding than the best parametric and concatenative systems for both English and Mandarin. A single WaveNet can capture the characteristics of many different speakers with equal fidelity, and can switch between them by conditioning on the speaker identity. When trained to model music, we find that it generates novel and often highly realistic musical fragments. We also show that it can be employed as a discriminative model, returning promising results for phoneme recognition._ 

The paper is based on
- [Pixel Recurrent Neural Networks](http://arxiv.org/abs/1601.06759) (ICML 2016 Best paper award)
- [Conditional Image Generation with PixelCNN Decoders](http://arxiv.org/abs/1606.05328) (NIPS 2016)

**Comment by leezu** [comment]
Thanks for voting.

I discussed with @sxjscience and we would like to proceed as follows.

Please everyone read
- [Pixel Recurrent Neural Networks](http://arxiv.org/abs/1601.06759) (ICML 2016 Best paper award)
- [Conditional Image Generation with PixelCNN Decoders](http://arxiv.org/abs/1606.05328) (NIPS 2016)
  for Friday.

Please take note of parts that are unclear or that you don't understand. We will go through the papers and discuss all doubts so that we can all gain a better understanding. We can also discuss other questions as long as they have a relevance to most of us (e.g. are related to ML)!

For now we got room 2131B from 10:30am to noon.
